spring:
  application:
    name: jigeum-api

  datasource:
    url: jdbc:postgresql://localhost:5432/jigeum_db
    username: ${DB_USERNAME:leesinseong}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    threads:
      max: 200

google:
  places:
    api-key: ${GOOGLE_API_KEY:AIzaSyDeBXJG6_YTuKnyHoRj6h0NgKWfLxyH5oE}
    base-url: https://places.googleapis.com
    language: ko
    timeout-seconds: 10
    max-retries: 3

logging:
  level:
    root: INFO
    com.jigeumopen.jigeum: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  file:
    name: logs/jigeum-api.log
    max-size: 10MB
    max-history: 7
