spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: jigeum-api

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    url: jdbc:postgresql://localhost:5432/jigeum_db
    username: ${DB_USERNAME:leesinseong}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: 3000ms

  cache:
    type: redis
    redis:
      time-to-live: 1800000
      cache-null-values: false

  webflux:
    base-path: /api

  threads:
    virtual:
      enabled: ${VIRTUAL_THREAD_ENABLED:true}

  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: batch-scheduler-
    execution:
      pool:
        core-size: ${VIRTUAL_THREAD_PARALLELISM:100}
        max-size: ${VIRTUAL_THREAD_PARALLELISM:100}
        queue-capacity: 100

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

google:
  places:
    api-key: ${GOOGLE_API_KEY}
    language: ko
    timeout-seconds: 10

batch:
  scheduler:
    enabled: ${BATCH_SCHEDULER_ENABLED:false}
    collect-cron: "0 0 3 L * *"
    process-cron: "0 0 5 L * *"  #
    retry-cron: "0 0 4 L * *"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: none

logging:
  level:
    root: INFO
    com.jigeumopen.jigeum: ${LOG_LEVEL:DEBUG}
    com.jigeumopen.jigeum.batch: DEBUG
    com.jigeumopen.jigeum.infrastructure.client: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n"
  file:
    name: logs/jigeum-api.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 1GB
