spring:
  application:
    name: jigeum-api

  datasource:
    url: jdbc:postgresql://localhost:5432/jigeum_db
    username: ${DB_USERNAME}
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        default_batch_fetch_size: 50

  webflux:
    base-path: /api

server:
  port: 8080

google:
  places:
    api-key: ${GOOGLE_API_KEY}
    language: ko
    timeout-seconds: 10

logging:
  level:
    root: INFO
    com.jigeumopen.jigeum: ${LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
