spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: jigeum-api

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    url: jdbc:postgresql://localhost:5432/jigeum_db
    username: ${DB_USERNAME:leesinseong}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  webflux:
    base-path: /api

  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: batch-scheduler-

server:
  port: 8080

google:
  places:
    api-key: ${GOOGLE_API_KEY}
    language: ko
    timeout-seconds: 10

batch:
  scheduler:
    enabled: ${BATCH_SCHEDULER_ENABLED:false}
    collect-cron: "0 0 3 L * *"
    process-cron: "0 0 5 L * *"
    retry-cron: "0 0 4 L * *"

logging:
  level:
    root: INFO
    com.jigeumopen.jigeum: ${LOG_LEVEL:DEBUG}
    com.jigeumopen.jigeum.batch: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: logs/jigeum-api.log
    max-size: 10MB
    max-history: 30
