spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jigeum_db
    username: leesinseong
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

google:
  places:
    api-key: AIzaSyDeBXJG6_YTuKnyHoRj6h0NgKWfLxyH5oE
    base-url: https://places.googleapis.com  # ??!

logging:
  level:
    com.jigeumopen.jigeum: DEBUG
    reactor.netty: DEBUG
